### ISSUE TITLE
请问能不能给这个lyx模板写个使用说明

### ISSUE THREAD

**Issue by nirvana6** [iphyer/UCASThesisTemplete#1]
你好。我是一个lyx新手，也没有Latex经验。

请问您能不能写一个针对新手的教程。

我在网上找到的教程都是说把cls文件和bst文件拷贝到系统的相关文件夹下，把lyx文件拷贝到.lyx下，可你给的这个模板有很多其它后缀名的文件，不知道它们都有什么用途。

**Comment by iphyer** [comment]
我看看，你是在windows下吗?因为我没用过Lyx，所以不知道能不能解决这个问题。我给的这个模板也是基于Latex开发的。你是必须在Lyx中使用?cls文件和bst文件确实Latex模板必须的文件，其他的文件后缀名是指什么？

**Comment by iphyer** [comment]
是这样的，我都是直接使用Linux文件夹中的`CASLyXThesis.tex`,然后用`make`命令。你可以运行成功这个文件吗?对于Lyx用的不多，但是如果你想知道每个文件的作用我可以解释给你。cls的定义一些命令和风格的，bst是用来对于文献做处理的。其他的文件很多都是在做布局的工作，你可以跳过去。

首先一个问题是你可以运行起来这个文件吗？就是比如直接编译出一个文件？

**Comment by nirvana6** [comment]
我现在的问题是，在Ubuntu下，运行命令`xelatex CASLyXThesis.tex`，出现错误：

![selection_052](https://cloud.githubusercontent.com/assets/2957421/10867569/4d41bb04-80a4-11e5-9972-480b01916b55.png)

PS. 并不是非用lyx不可，只是觉得用这个快速得写笔记会比敲latex代码方便很多。因为有的时候敲代码确实干扰思考。

**Comment by iphyer** [comment]
连续按下回车直到可以继续编译即可。
这是你的texlive使用了更高版本的原因。

恩。
没有用过Lyx,确实不太了解，你可以问问这个学长mgcgogo@gmail.com，因为他是基于Lyx做的这个模板我引用了他的code ，但是没有用Lyx。

**Comment by nirvana6** [comment]
一直摁“回车”没有用，会在中文字体处卡住。

谢谢。我现在正在熟悉Latex。Lyx的布局似乎不太难，就是将Latex的一些类的映射Lyx的一些菜单。

**Comment by iphyer** [comment]
额，首先你要把Times New Roman还有后面的额一大堆中文字体配置出来。这个可能是一个出问题的地方。

我升级了texlive的版本，确实会有这个问题。大概要按三四次回车键才行，比如这样:

![screenshot - 2015 11 01 - 17 39 04](https://cloud.githubusercontent.com/assets/1913891/10868167/d76b05f4-80bf-11e5-9ec6-5c7266db468e.png)

我也不知道为什么。在我原来的低版本Texlive中确实没这个问题。

![screenshot - 2015 11 01 - 17 40 37](https://cloud.githubusercontent.com/assets/1913891/10868168/dbeb72b2-80bf-11e5-81a6-53ec1bb90580.png)

这样就可以编译完成了。

祝好！

**Comment by nirvana6** [comment]
谢谢你提供的思路。我下一步_配置中文字体_能够解决我的问题。
